import { colors } from './colors';

export const typography = {
  h1: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: 0.2,
    lineHeight: 34,
  },
  h2: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: 0.2,
    lineHeight: 30,
  },
  h3: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: 0.2,
    lineHeight: 26,
  },
  h4: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    letterSpacing: 0.2,
    lineHeight: 24,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  body: {
    fontSize: 16,
    fontWeight: '400',
    color: colors.text,
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  bodyMedium: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text,
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  bodySmall: {
    fontSize: 14,
    fontWeight: '400',
    color: colors.text,
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  caption: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSecondary,
    letterSpacing: 0.2,
    lineHeight: 16,
  },
  captionMedium: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.textSecondary,
    letterSpacing: 0.2,
    lineHeight: 16,
  },
  // Add the missing captionSmall style
  captionSmall: {
    fontSize: 10,
    fontWeight: '400',
    color: colors.textSecondary,
    letterSpacing: 0.2,
    lineHeight: 14,
  },
  button: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  buttonSmall: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.white,
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  link: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.primary,
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  linkSmall: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.primary,
    letterSpacing: 0.2,
    lineHeight: 20,
  },
};